// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: testdata/ping-service/api/testdata-service/v1/resources/testdata.resource.v1.proto

package resourcev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TestReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TestReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TestReqMultiError, or nil if none found.
func (m *TestReq) ValidateAll() error {
	return m.validate(true)
}

func (m *TestReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return TestReqMultiError(errors)
	}

	return nil
}

// TestReqMultiError is an error wrapping multiple validation errors returned
// by TestReq.ValidateAll() if the designated constraints aren't met.
type TestReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestReqMultiError) AllErrors() []error { return m }

// TestReqValidationError is the validation error returned by TestReq.Validate
// if the designated constraints aren't met.
type TestReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestReqValidationError) ErrorName() string { return "TestReqValidationError" }

// Error satisfies the builtin error interface
func (e TestReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestReqValidationError{}

// Validate checks the field values on TestResp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TestResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TestRespMultiError, or nil
// if none found.
func (m *TestResp) ValidateAll() error {
	return m.validate(true)
}

func (m *TestResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TestRespMultiError(errors)
	}

	return nil
}

// TestRespMultiError is an error wrapping multiple validation errors returned
// by TestResp.ValidateAll() if the designated constraints aren't met.
type TestRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestRespMultiError) AllErrors() []error { return m }

// TestRespValidationError is the validation error returned by
// TestResp.Validate if the designated constraints aren't met.
type TestRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestRespValidationError) ErrorName() string { return "TestRespValidationError" }

// Error satisfies the builtin error interface
func (e TestRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestRespValidationError{}

// Validate checks the field values on TestRespData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TestRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestRespData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TestRespDataMultiError, or
// nil if none found.
func (m *TestRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *TestRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	if len(errors) > 0 {
		return TestRespDataMultiError(errors)
	}

	return nil
}

// TestRespDataMultiError is an error wrapping multiple validation errors
// returned by TestRespData.ValidateAll() if the designated constraints aren't met.
type TestRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestRespDataMultiError) AllErrors() []error { return m }

// TestRespDataValidationError is the validation error returned by
// TestRespData.Validate if the designated constraints aren't met.
type TestRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestRespDataValidationError) ErrorName() string { return "TestRespDataValidationError" }

// Error satisfies the builtin error interface
func (e TestRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestRespDataValidationError{}
